### ISSUE TITLE
EACH person makes two new features (Possibly with .js and python no HTML or CSS)

### ISSUE THREAD

**Issue by allisonthuang** [christinlee367/n225_FireEradicatorsTheSequel#83]

**Comment by christinlee367** [comment]
- [ ] PBL #1 Pull Request: #95 
[link](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/forecasting.html)

- integration of SASS/SCSS 
- Javascript and html
- weather related

- [ ] PBL #2

- API integration also related to the weather (country and area attributes)
