### ISSUE TITLE
Week 5 & 7 - PBL/Crossover Review Ticket

### ISSUE THREAD

**Issue by allisonthuang** [christinlee367/n225_FireEradicatorsTheSequel#98]
**Our Links to Tangibles:**
- [CRUD Personalization](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/commit/58f185360212fcb0816d9c3869f58dc895f39e50) (Neha)
- [HTML](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/forecasting.html), [JavaScript](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/foreCast.js), [SCSS/SASS convert to CSS](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/style1.css), and [API](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/christinaWeath.html) (Christina)
- [Blueprint about me pages](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/commit/2d93ff7419e97264710f24039a808451e9fedfe0) and [API](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/commit/d3345da2c791bf6b1fee20c6801afb87077fb1c4) (Gigi)
- [PBL #1](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/2f0114358c160f183ba78381582752cdf005615c/Anika%20test%20games.py) [PBL #2](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/2f0114358c160f183ba78381582752cdf005615c/templates/layouts/customCSS.css) (Anika)
- [Worked a lot on earthquake Rating & Blueprints](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/tree/main/earthquakerating) and [Disaster Map w/.js like count button](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/week4/disastermap.html)(Allison)
- [Jekyll vocab highlights for our project (The links to our wiki vocab are on the static site)](https://allisonthuang.github.io/) (Allison)
- [Blueprint illustrations in main.py and new .py](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/main.py#L9-L25) (Gigi/Allison)

**Our Grading of Turtles (Crossover team):**

Link to crossover group's deployed site: [dnhsresources.cf](https://dnhsresources.cf/)
Link to crossover group's review ticket: [Link](https://github.com/sonakshibhalla/tri2_turtles.github.io/issues/146)
Link to our video on crossover group's site: [Link](https://youtu.be/gdBiuVj16z4) (Allison)

1. Evaluation of Crossover Team PBL key features
2. Evaluation of Github Pages, Jekyll, WIKI - focus will be on quality of Vocabulary from Week 6 as key review item
3. Evaluation of Sassy / Bootstrap - under the hood on CSS usage and capitalizing on Bootstrap features, as well as runtime quality
4. Evaluation of Async Operation - runtime and under the hood usage of JavaScript and Fetch, as well as how things are updated on screen
5. Evaluation of CRUD in Database - runtime and behind the scenes using CRUD operations, as well as progress on database personalization
6. Extra or Replacement Features (Blueprint illustration/demonstration, searching/filtering data)

**Total Score: 5.65/6**

| Topic  | Total Score    | Justification    |
| :---------:  | :---------| :------ |
| # 1  | 0.75/1 |  I don't see much PBL features that are code more like python or .js.  A lot of them are embeds and links, but I do see interesting things like the API and reveal answer. |
| # 2  | 1/1 |  Jekyll page is customized by Sonakshi. I see the vocab review on the Wiki, but you should put it on your static site too. |
| # 3 | 1/1 | I thought this was a really strong point about your guys's site. I really liked all the different layouts and use of columns. In terms of layout, the carousel was a cool addition and visual interruption in your site to create interest. |
| # 4  | 1/1 | The Async operation works, and things are updated on screen. The searchbar works as well. | 
| # 5  | 1/1 | CRUD database is fully functional. I see changes to style, as well as customization to your PBL topic. |
| # 6  | 0.90/1 | The searchbar to filter data from the CRUD database works. I do see one imported blueprint on your main.py for the CRUD, but one thing you could do is make separate .py files for your about pages (essentially uncluttering the main.py and creating overarching routes for each person) |

**Comment by christinlee367** [comment]
- [ ] PBL 1 Pull Request: #95 
[link](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/forecasting.html)

- integration of SASS/SCSS 
- Javascript [js](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/foreCast.js) HTML [SCSS](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/style1.css)
- weather related

- [ ] PBL #2
[API](https://github.com/christinlee367/n225_FireEradicatorsTheSequel/blob/main/templates/pbl/TT7/christinaWeath.html)
- API integration also related to the weather (country and area attributes)

**Comment by shreya-ahujaa** [comment]
**Grading of Fire Eradicators from Turtles:**

1. Evaluation of Crossover Team PBL key features
2. Evaluation of Github Pages, Jekyll, WIKI - focus will be on quality of Vocabulary from Week 6 as key review item
3. Evaluation of Sassy / Bootstrap - under the hood on CSS usage and capitalizing on Bootstrap features, as well as runtime quality
4. Evaluation of Async Operation - runtime and under the hood usage of JavaScript and Fetch, as well as how things are updated on screen
5. Evaluation of CRUD in Database - runtime and behind the scenes using CRUD operations, as well as progress on database personalization
6. Extra or Replacement Features (Blueprint illustration/demonstration, searching/filtering data)

**Total Score: 5.45/6**

| Topic  | Total Score    | Justification    |
| :---------:  | :---------| :------ |
| # 1  | 1/1 |  I see a lot of PBL Features, and there are many pages that add more to your website. Most of them relate, and the ones that don't show that you have been experimenting with new things! |
| # 2  | 0.9/1 |  The Jekyll Pages are up, but there does not seem to be that much customization on the page itself. There is only a home page, but it doesn't seem updated --> maybe try to add some new pages that add to the Jekyll! |
| # 3 | 1/1 | I thought the visuals on your website were very nice and aesthetic, as the theme of the website seemed to be constant across all the pages. The runtime quality was great, and all the pieces related to your main theme.  |
| # 4  | 1/1 | The Async operation works, and the Database is able to be updated with the delete, add, change, and create of a whole new one. | 
| # 5  | 0.80/1 | The database is working, and is getting the elements inputted, but there does not seem to be any customization on the database itself. Maybe try to make the CRUD database more applicable to the website (I saw that you started to change the titles, but also just change the names and the actual values so it looks put together) |
| # 6  | 0.75/1 | I see that there is a searchbar on the top of the page, which I thought was nice. However, the searchbar does not work so I just took off some points as there is no functionality.  |
